# fly.toml app configuration file generated for dittofeed-temporal-staging on 2024-09-10T17:25:51+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'dittofeed-temporal'
primary_region = 'bom'

[processes]
  server = '/etc/temporal/entrypoint.sh autosetup'

[build]

[[services]]
  protocol = 'tcp'
  internal_port = 7233
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ['server']

  [[services.ports]]
    port = 7233

  [[services.tcp_checks]]
    interval = '10s'
    timeout = '2s'
    grace_period = '5s'

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 2